#%RAML 1.0 NamedExample

value: | 
  
  {
  fastPathEnabled: false,
  numberRecordsFailed: 0,
  externalIdFieldName: "INC_ExtId_SIPanel__c",
  systemModstamp: |2021-02-02T08:14:05|,
  numberRetries: 0,
  apiVersion: 46.0,
  id: "7501j000004vCFTAA2",
  state: "Open",
  numberBatchesQueued: 0,
  totalProcessingTime: 0,
  contentType: "CSV",
  createdById: "0051j000005C3l5AAC",
  numberRecordsProcessed: 0,
  apiActiveProcessingTime: 0,
  concurrencyMode: "Serial",
  numberBatchesFailed: 0,
  apexProcessingTime: 0,
  createdDate: |2021-02-02T08:14:05|,
  assignmentRuleId: null,
  numberBatchesInProgress: 0,
  operation: "upsert",
  numberBatchesTotal: 0,
  object: "Fidelisation__c",
  numberBatchesCompleted: 0
  }