# Environment specific properties
environment:
 name: "dev"
  
api:
  name: "${application.name}-${environment.name}"
  id: "795526"
  version: "v1"

http:
  private:
    port: "8091"
  timeout: "999999999"
  listener:
    path: "/api/${api.name}/${api.version}/*"

https:
  port: "8092"
  listener:
    path: "/api/${api.name}/${api.version}/*"

config:
  salesforce:
    authorizationURL: "https://test.salesforce.com/services/Soap/u/50.0"
    username: "mulesoft.api@garance.fr.recette"
    password: "${secure::passwords.sfdcPass}"
    securityToken: "4NHYgGPP2eCmNbVDiU9obI1u"
    timeout: "900000000"
    
# Common properties
common:
  audit:
    role:
      logStart: "true"
      logEnd: "true"
      logInfo: "true"
      logWarning: "true"
      logError: "true"
      logDebug: "true"
    defaultLogPayloadLogic: "ALWAYS"